#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import datetime
import subprocess
import time

os.chdir(os.path.dirname(__file__))

reload(sys)
sys.setdefaultencoding('utf-8')

end_date = datetime.datetime.now().strftime('%Y-%m-%d')
start_date = (
    datetime.datetime.now() -
    datetime.timedelta(
        days=5)).strftime('%Y-%m-%d')


from ivod.commands import load_configurations, download_meetings
config = load_configurations('config.json')
download_meetings(config, None, start_date, end_date)
