#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
from optparse import OptionParser
from ivod.commands import download_single_high_quality_video

reload(sys)
sys.setdefaultencoding('utf-8')


def main():
    usage = "usage: %prog [options]"
    parser = OptionParser(usage)
    parser.add_option("-u", "--url", dest="url",
                      help='IVOD Url')
    (options, args) = parser.parse_args()

    if not options.url:
        print 'Please input url.'
        sys.exit(1)
    download_single_high_quality_video(options.url)

if __name__ == '__main__':
    main()
